<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit219f5f6ec579a84ab45f4ff05a0bdd6c
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit219f5f6ec579a84ab45f4ff05a0bdd6c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit219f5f6ec579a84ab45f4ff05a0bdd6c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit219f5f6ec579a84ab45f4ff05a0bdd6c::$classMap;

        }, null, ClassLoader::class);
    }
}
